In [1]:
import pandas

In [ ]:
df_1_survey = pandas.read_csv("../resources/SongSurvey Database - SliderResponses.csv")

In [ ]:
# df_2_songs = pandas.read_csv("./19332_Spotify_Songs.csv", encoding="MacRoman")
df_2_songs = pandas.read_csv("../out/clean_data.csv")

In [11]:
df_merged = pandas.merge(df_1_survey, df_2_songs, how='left', left_on='song_url', right_on='song_link', validate='m:1')

In [24]:
df_merged.columns

Index(['timestamp', 'email', 'song_name', 'song_url', 'before: sad to happy',
       'before: calm to energetic', 'before: relaxed to stressed',
       'after: sad to happy', 'after: calm to energetic',
       'after: relaxed to stressed', 'Unnamed: 0', 'song_link', 'id',
       'release_year', 'duration_ms.x', 'explicit', 'name', 'popularity',
       'danceability', 'energy', 'key', 'loudness', 'mode', 'speechiness',
       'acousticness', 'instrumentalness', 'liveness', 'valence', 'tempo',
       'time_signature'],
      dtype='object')

In [26]:

df_merged.head()

,timestamp,email,song_name,song_url,before: sad to happy,before: calm to energetic,before: relaxed to stressed,after: sad to happy,after: calm to energetic,after: relaxed to stressed,...,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature
0,2026-02-09 16:35:14,ashly@gmail.com,Kolors,https://open.spotify.com/track/4IOYk6epkzXT38U...,0.09,0.10,0.08,0.33,0.37,0.28,...,2.0,-11.064,0.0,0.2050,0.26300,0.000002,0.2280,0.636,129.582,4.0
1,2026-02-09 16:49:31,laperrona@gmail.com,Levitating,https://open.spotify.com/track/39LLxExYz6ewLAc...,0.29,0.09,0.52,1.00,0.81,0.10,...,6.0,-2.278,0.0,0.0753,0.05610,0.000000,0.2130,0.914,103.014,4.0
2,2026-02-09 17:12:01,10978411@uvu.edu,Surrender,https://open.spotify.com/track/2ccUQnjjNWT0rsN...,0.17,0.06,0.30,0.14,0.15,0.25,...,0.0,-7.081,1.0,0.0411,0.00717,0.000009,0.6590,0.869,133.849,4.0
3,2026-02-09 17:36:24,zaq.holdsworth@gmail.com,Victoria,https://open.spotify.com/track/2BxzmBb2uqwnpyV...,0.74,0.28,0.18,0.64,0.09,0.02,...,11.0,-4.433,0.0,0.1050,0.54200,0.000000,0.2030,0.568,88.042,4.0
4,2026-02-09 18:17:38,Henry.Desposorio@uvu.edu,"Eleg√≠ (feat. Farruko, Anuel AA, Sech, D√≠melo...",https://open.spotify.com/track/3oCghu20Kto5Xcu...,0.70,0.40,0.30,0.75,0.45,0.25,...,0.0,-4.727,1.0,0.0883,0.16000,0.000828,0.0598,0.738,172.044,4.0

In [ ]:
df_merged.to_csv('../out/merged_data.csv')

In [ ]:
pandas.read_csv('../out/merged_data.csv')

,Unnamed: 0.1,timestamp,email,song_name,song_url,before: sad to happy,before: calm to energetic,before: relaxed to stressed,after: sad to happy,after: calm to energetic,...,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature
0,0,2026-02-09 16:35:14,ashly@gmail.com,Kolors,https://open.spotify.com/track/4IOYk6epkzXT38U...,0.09,0.10,0.08,0.33,0.37,...,2.0,-11.064,0.0,0.2050,0.26300,0.000002,0.2280,0.6360,129.582,4.0
1,1,2026-02-09 16:49:31,laperrona@gmail.com,Levitating,https://open.spotify.com/track/39LLxExYz6ewLAc...,0.29,0.09,0.52,1.00,0.81,...,6.0,-2.278,0.0,0.0753,0.05610,0.000000,0.2130,0.9140,103.014,4.0
2,2,2026-02-09 17:12:01,10978411@uvu.edu,Surrender,https://open.spotify.com/track/2ccUQnjjNWT0rsN...,0.17,0.06,0.30,0.14,0.15,...,0.0,-7.081,1.0,0.0411,0.00717,0.000009,0.6590,0.8690,133.849,4.0
3,3,2026-02-09 17:36:24,zaq.holdsworth@gmail.com,Victoria,https://open.spotify.com/track/2BxzmBb2uqwnpyV...,0.74,0.28,0.18,0.64,0.09,...,11.0,-4.433,0.0,0.1050,0.54200,0.000000,0.2030,0.5680,88.042,4.0
4,4,2026-02-09 18:17:38,Henry.Desposorio@uvu.edu,"Eleg√≠ (feat. Farruko, Anuel AA, Sech, D√≠melo...",https://open.spotify.com/track/3oCghu20Kto5Xcu...,0.70,0.40,0.30,0.75,0.45,...,0.0,-4.727,1.0,0.0883,0.16000,0.000828,0.0598,0.7380,172.044,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81,81,2026-02-25 15:58:56,10941870@uvu.edu,Right My Wrongs,https://open.spotify.com/track/5rgrBsAFYMun6yh...,0.23,0.05,0.65,0.63,0.53,...,1.0,-8.065,1.0,0.0463,0.34500,0.000000,0.1570,0.2900,132.609,4.0
82,82,2026-02-25 17:49:01,dcturgeon22@gmail.com,"UP! (feat. Chris Brown, Pleasure P) (R&B Remix...",https://open.spotify.com/track/6tZmrNnFao9ofNv...,0.65,0.20,0.45,0.60,0.25,...,1.0,-10.390,1.0,0.1310,0.40900,0.000000,0.6160,0.4980,96.922,4.0
83,83,2026-02-26 17:15:14,jrmcnairy@gmail.com,Out in Space (feat. Quavo),https://open.spotify.com/track/3bqU32NjjtMeJ7d...,0.32,0.55,0.90,0.85,0.83,...,9.0,-5.334,1.0,0.0472,0.04740,0.000000,0.3370,0.1260,129.976,4.0
84,84,2026-03-01 00:08:57,segretaincelestine@gmail.com,Real Love x Sunchyme (feat. Jess Glynne) [VIP ...,https://open.spotify.com/track/17fPLuA4TttWwfN...,0.80,0.50,0.30,0.90,0.60,...,2.0,-6.333,1.0,0.0497,0.01720,0.000000,0.5440,0.4640,125.004,4.0
85,85,2026-03-02 15:02:33,libbymortslam@gmail.com,Zanarkand (Final Fantasy X),https://open.spotify.com/track/7u5cNg0E6yqthRi...,0.92,1.00,1.00,0.41,0.09,...,11.0,-14.480,0.0,0.0365,0.93000,0.872000,0.0947,0.0922,80.729,3.0