In [1]:
import pandas

In [2]:
df_1_survey = pandas.read_csv("../resources/SongSurvey Database - SliderResponses.csv")

In [3]:
# df_2_songs = pandas.read_csv("./19332_Spotify_Songs.csv", encoding="MacRoman")
df_2_songs = pandas.read_csv("../out/clean_data.csv")

In [4]:
df_merged = pandas.merge(df_1_survey, df_2_songs, how='left', left_on='song_url', right_on='song_link', validate='m:1')

In [5]:
df_merged.columns

Index(['timestamp', 'email', 'song_name', 'song_url', 'before: sad to happy',
       'before: calm to energetic', 'before: relaxed to stressed',
       'after: sad to happy', 'after: calm to energetic',
       'after: relaxed to stressed', 'Unnamed: 0', 'song_link', 'id',
       'release_year', 'duration_ms.x', 'explicit', 'name', 'popularity',
       'danceability', 'energy', 'key', 'loudness', 'mode', 'speechiness',
       'acousticness', 'instrumentalness', 'liveness', 'valence', 'tempo',
       'time_signature'],
      dtype='object')

In [6]:

df_merged.head(n=10)

,timestamp,email,song_name,song_url,before: sad to happy,before: calm to energetic,before: relaxed to stressed,after: sad to happy,after: calm to energetic,after: relaxed to stressed,...,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature
0,2026-02-09 16:35:14,ashly@gmail.com,Kolors,https://open.spotify.com/track/4IOYk6epkzXT38U...,0.09,0.10,0.08,0.33,0.37,0.28,...,2.0,-11.064,0.0,0.2050,0.26300,0.000002,0.2280,0.636,129.582,4.0
1,2026-02-09 16:49:31,laperrona@gmail.com,Levitating,https://open.spotify.com/track/39LLxExYz6ewLAc...,0.29,0.09,0.52,1.00,0.81,0.10,...,6.0,-2.278,0.0,0.0753,0.05610,0.000000,0.2130,0.914,103.014,4.0
2,2026-02-09 17:12:01,10978411@uvu.edu,Surrender,https://open.spotify.com/track/2ccUQnjjNWT0rsN...,0.17,0.06,0.30,0.14,0.15,0.25,...,0.0,-7.081,1.0,0.0411,0.00717,0.000009,0.6590,0.869,133.849,4.0
3,2026-02-09 17:36:24,zaq.holdsworth@gmail.com,Victoria,https://open.spotify.com/track/2BxzmBb2uqwnpyV...,0.74,0.28,0.18,0.64,0.09,0.02,...,11.0,-4.433,0.0,0.1050,0.54200,0.000000,0.2030,0.568,88.042,4.0
4,2026-02-09 18:17:38,Henry.Desposorio@uvu.edu,"Eleg√≠ (feat. Farruko, Anuel AA, Sech, D√≠melo...",https://open.spotify.com/track/3oCghu20Kto5Xcu...,0.70,0.40,0.30,0.75,0.45,0.25,...,0.0,-4.727,1.0,0.0883,0.16000,0.000828,0.0598,0.738,172.044,4.0
5,2026-02-13 15:45:12,nathanielmeads@gmail.com,Canadian Goose,https://open.spotify.com/track/1MNdfH2KC5LdEde...,0.67,0.23,0.10,0.67,0.23,0.10,...,1.0,-7.604,0.0,0.1970,0.08550,0.000000,0.1030,0.238,153.060,4.0
6,2026-02-13 15:52:04,10912040@uvu.edu,Unstoppable,https://open.spotify.com/track/1yvMUkIOTeUNtNW...,0.65,0.45,0.71,0.52,0.46,0.68,...,9.0,-4.839,1.0,0.0779,0.11200,0.000373,0.1010,0.260,173.799,4.0
7,2026-02-13 17:00:40,10944757@uvu.edu,Raise a Hallelujah (Live),https://open.spotify.com/track/0YxrPdW9NpNFtqh...,0.81,0.30,0.20,0.75,0.40,0.35,...,1.0,-4.431,1.0,0.0400,0.00410,0.000000,0.1340,0.291,81.972,4.0
8,2026-02-13 18:06:55,10946730@uvu.edu,Juke Jam (feat. Justin Bieber & Towkio),https://open.spotify.com/track/3eze1OsZ1rqeXkK...,0.00,0.43,1.00,0.00,0.29,0.76,...,5.0,-9.349,1.0,0.3240,0.71600,0.000000,0.0853,0.558,95.063,1.0
9,2026-02-14 00:14:31,10969781@uvu.edu,I Mean It (feat. Remo),https://open.spotify.com/track/6jmTHeoWvBaSrwW...,0.74,0.39,0.20,0.65,0.37,0.18,...,10.0,-6.008,1.0,0.1290,0.12500,0.000000,0.1360,0.142,140.000,4.0

In [7]:
emotional_axes = ['sad to happy', 'calm to energetic', 'relaxed to stressed']

for emotional_axis in emotional_axes:
    before = df_merged[f'before: {emotional_axis}']
    after = df_merged[f'after: {emotional_axis}']
    df_merged[f'delta: {emotional_axis}'] = after - before

In [8]:
df_merged.to_csv('../out/merged_data.csv')

In [9]:
# Checking if it saved correctly
df_merged_from_csv = pandas.read_csv('../out/merged_data.csv')
df_merged_from_csv.head(n=10)

,Unnamed: 0.1,timestamp,email,song_name,song_url,before: sad to happy,before: calm to energetic,before: relaxed to stressed,after: sad to happy,after: calm to energetic,...,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,delta: sad to happy,delta: calm to energetic,delta: relaxed to stressed
0,0,2026-02-09 16:35:14,ashly@gmail.com,Kolors,https://open.spotify.com/track/4IOYk6epkzXT38U...,0.09,0.10,0.08,0.33,0.37,...,0.2050,0.26300,0.000002,0.2280,0.636,129.582,4.0,0.24,0.27,0.20
1,1,2026-02-09 16:49:31,laperrona@gmail.com,Levitating,https://open.spotify.com/track/39LLxExYz6ewLAc...,0.29,0.09,0.52,1.00,0.81,...,0.0753,0.05610,0.000000,0.2130,0.914,103.014,4.0,0.71,0.72,-0.42
2,2,2026-02-09 17:12:01,10978411@uvu.edu,Surrender,https://open.spotify.com/track/2ccUQnjjNWT0rsN...,0.17,0.06,0.30,0.14,0.15,...,0.0411,0.00717,0.000009,0.6590,0.869,133.849,4.0,-0.03,0.09,-0.05
3,3,2026-02-09 17:36:24,zaq.holdsworth@gmail.com,Victoria,https://open.spotify.com/track/2BxzmBb2uqwnpyV...,0.74,0.28,0.18,0.64,0.09,...,0.1050,0.54200,0.000000,0.2030,0.568,88.042,4.0,-0.10,-0.19,-0.16
4,4,2026-02-09 18:17:38,Henry.Desposorio@uvu.edu,"Eleg√≠ (feat. Farruko, Anuel AA, Sech, D√≠melo...",https://open.spotify.com/track/3oCghu20Kto5Xcu...,0.70,0.40,0.30,0.75,0.45,...,0.0883,0.16000,0.000828,0.0598,0.738,172.044,4.0,0.05,0.05,-0.05
5,5,2026-02-13 15:45:12,nathanielmeads@gmail.com,Canadian Goose,https://open.spotify.com/track/1MNdfH2KC5LdEde...,0.67,0.23,0.10,0.67,0.23,...,0.1970,0.08550,0.000000,0.1030,0.238,153.060,4.0,0.00,0.00,0.00
6,6,2026-02-13 15:52:04,10912040@uvu.edu,Unstoppable,https://open.spotify.com/track/1yvMUkIOTeUNtNW...,0.65,0.45,0.71,0.52,0.46,...,0.0779,0.11200,0.000373,0.1010,0.260,173.799,4.0,-0.13,0.01,-0.03
7,7,2026-02-13 17:00:40,10944757@uvu.edu,Raise a Hallelujah (Live),https://open.spotify.com/track/0YxrPdW9NpNFtqh...,0.81,0.30,0.20,0.75,0.40,...,0.0400,0.00410,0.000000,0.1340,0.291,81.972,4.0,-0.06,0.10,0.15
8,8,2026-02-13 18:06:55,10946730@uvu.edu,Juke Jam (feat. Justin Bieber & Towkio),https://open.spotify.com/track/3eze1OsZ1rqeXkK...,0.00,0.43,1.00,0.00,0.29,...,0.3240,0.71600,0.000000,0.0853,0.558,95.063,1.0,0.00,-0.14,-0.24
9,9,2026-02-14 00:14:31,10969781@uvu.edu,I Mean It (feat. Remo),https://open.spotify.com/track/6jmTHeoWvBaSrwW...,0.74,0.39,0.20,0.65,0.37,...,0.1290,0.12500,0.000000,0.1360,0.142,140.000,4.0,-0.09,-0.02,-0.02

In [10]:
df_merged.columns

Index(['timestamp', 'email', 'song_name', 'song_url', 'before: sad to happy',
       'before: calm to energetic', 'before: relaxed to stressed',
       'after: sad to happy', 'after: calm to energetic',
       'after: relaxed to stressed', 'Unnamed: 0', 'song_link', 'id',
       'release_year', 'duration_ms.x', 'explicit', 'name', 'popularity',
       'danceability', 'energy', 'key', 'loudness', 'mode', 'speechiness',
       'acousticness', 'instrumentalness', 'liveness', 'valence', 'tempo',
       'time_signature', 'delta: sad to happy', 'delta: calm to energetic',
       'delta: relaxed to stressed'],
      dtype='object')

Just exploring the data

In [11]:
# from matplotlib import pyplot as plt

In [12]:
# # fig = plt.figure()
# # ax = fig.add_subplot(projection='3d')
# x = df_merged['delta sad to happy']
# y = df_merged['delta calm to energetic']
# z = df_merged['delta relaxed to stressed']
# # ax.scatter3D(x, y, z)
# SIZE = 3
# plt.scatter(x, y, s=SIZE)
# plt.show()
# plt.scatter(y, z, s=SIZE)
# plt.show()
# plt.scatter(x, z, s=SIZE)