In [2]:
import pandas

In [13]:
df = pandas.read_csv('../out/merged_data.csv')
df.head(3)

,Unnamed: 0.1,timestamp,email,song_name,song_url,before: sad to happy,before: calm to energetic,before: relaxed to stressed,after: sad to happy,after: calm to energetic,...,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,delta: sad to happy,delta: calm to energetic,delta: relaxed to stressed
0,0,2026-02-09 16:35:14,ashly@gmail.com,Kolors,https://open.spotify.com/track/4IOYk6epkzXT38U...,0.09,0.10,0.08,0.33,0.37,...,0.2050,0.26300,0.000002,0.228,0.636,129.582,4.0,0.24,0.27,0.20
1,1,2026-02-09 16:49:31,laperrona@gmail.com,Levitating,https://open.spotify.com/track/39LLxExYz6ewLAc...,0.29,0.09,0.52,1.00,0.81,...,0.0753,0.05610,0.000000,0.213,0.914,103.014,4.0,0.71,0.72,-0.42
2,2,2026-02-09 17:12:01,10978411@uvu.edu,Surrender,https://open.spotify.com/track/2ccUQnjjNWT0rsN...,0.17,0.06,0.30,0.14,0.15,...,0.0411,0.00717,0.000009,0.659,0.869,133.849,4.0,-0.03,0.09,-0.05

In [7]:
labels = df.columns
labels

Index(['Unnamed: 0.1', 'timestamp', 'email', 'song_name', 'song_url',
       'before: sad to happy', 'before: calm to energetic',
       'before: relaxed to stressed', 'after: sad to happy',
       'after: calm to energetic', 'after: relaxed to stressed', 'Unnamed: 0',
       'song_link', 'id', 'release_year', 'duration_ms.x', 'explicit', 'name',
       'popularity', 'danceability', 'energy', 'key', 'loudness', 'mode',
       'speechiness', 'acousticness', 'instrumentalness', 'liveness',
       'valence', 'tempo', 'time_signature', 'delta: sad to happy',
       'delta: calm to energetic', 'delta: relaxed to stressed'],
      dtype='object')

In [10]:
X = df.loc[
    :,
    [
        'release_year', 'duration_ms.x', 'explicit', 
        'mode', 'speechiness', 'acousticness',
        'instrumentalness', 'liveness', 'valence',
        'tempo', 'time_signature'
    ]
] 
X.head(3)

,release_year,duration_ms.x,explicit,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature
0,2016,177855,False,0.0,0.2050,0.26300,0.000002,0.228,0.636,129.582,4.0
1,2020,203807,False,0.0,0.0753,0.05610,0.000000,0.213,0.914,103.014,4.0
2,1978,253733,False,1.0,0.0411,0.00717,0.000009,0.659,0.869,133.849,4.0

In [12]:
Y = df.loc[
    :,
    [
        'delta: sad to happy',
        'delta: calm to energetic',
        'delta: relaxed to stressed'
    ]
] 
Y.head()

   delta: sad to happy  delta: calm to energetic  delta: relaxed to stressed
0                 0.24                      0.27                        0.20
1                 0.71                      0.72                       -0.42
2                -0.03                      0.09                       -0.05
3                -0.10                     -0.19                       -0.16
4                 0.05                      0.05                       -0.05