This is the file where models are created and tested as pre-product research.

In [64]:
import pandas

In [65]:
df = pandas.read_csv('../out/merged_data.csv')
# df.head(3)

In [66]:
labels = df.columns
# labels

In [67]:
X = df.loc[
    :,
    [
        'release_year', 'duration_ms.x', 'explicit', 
        'mode', 'speechiness', 'acousticness',
        'instrumentalness', 'liveness', 'valence',
        'tempo', 'time_signature'
    ]
] 
# X.head(3)

In [68]:
Y = df.loc[
    :,
    [
        'delta: sad to happy',
        'delta: calm to energetic',
        'delta: relaxed to stressed'
    ]
] 
# Y.head()

Split into training and not

Creating the model

In [142]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2)

In [145]:
from sklearn import linear_model
from sklearn.multioutput import MultiOutputRegressor

base_estimator = linear_model.LinearRegression()
model_linear = MultiOutputRegressor(base_estimator)
model_linear.fit(X_train, y_train)

model_linear.score(X_train, y_train)

0.29454666595517315

Another Model

In [144]:
from sklearn.ensemble import GradientBoostingRegressor

model_gradient_boost = MultiOutputRegressor(GradientBoostingRegressor())
model_gradient_boost.fit(X_train, y_train)
print("Training score")
print(model_gradient_boost.score(X_train, y_train))
print("Test score")
print(model_gradient_boost.score(X_test, y_test))

Training score
0.995194585971163
Test score
-0.6669093933755658

In [72]:
pandas.DataFrame(model_gradient_boost.predict(X_test)).head()

          0         1         2
0  0.112241  0.489046  0.184122
1 -0.023604  0.520731 -0.137995
2  0.025108  0.094846 -0.209929
3 -0.040813  0.181949 -0.884814
4 -0.007211  0.170681  0.116179

In [73]:
y_test.head()

    delta: sad to happy  delta: calm to energetic  delta: relaxed to stressed
11                 0.47                      0.71                        0.33
0                  0.24                      0.27                        0.20
79                 0.14                      0.13                        0.16
29                 0.56                     -0.14                       -0.14
66                -0.12                     -0.06                       -0.09

Trying to just predict one column

In [147]:
y = Y['delta: sad to happy']

# Assuming X contains features and y contains labels
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=2)

In [148]:
from sklearn.linear_model import LinearRegression

model_linear = LinearRegression()
model_linear.fit(X_train, y_train)

model_linear.score(X_train, y_train)

0.3032761880362427

In [155]:
y = Y['delta: calm to energetic']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

model_linear = LinearRegression()
model_linear.fit(X_train, y_train)

print("Training score")
print(model_linear.score(X_train, y_train))
print("Test score")
print(model_linear.score(X_test, y_test))

Training score
0.24685713588480407
Test score
0.13125208394118593

In [107]:
y = Y['delta: relaxed to stressed']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

from sklearn.linear_model import LinearRegression

model_linear = LinearRegression()
model_linear.fit(X_train, y_train)
print("Training score")
print(model_linear.score(X_train, y_train))
print("Test score")
print(model_linear.score(X_test, y_test))

Training score
0.27647241165501346
Test score
0.3119911654320112

In [159]:
from sklearn.model_selection import cross_val_score

cross_val_score(model_gradient_boost, X, Y)

array([-0.20460399, -0.06530869, -0.09652105, -0.76341442, -0.01154859])

In [253]:
from sklearn.neural_network import MLPRegressor

neural_net_model_1 = MLPRegressor(hidden_layer_sizes=(10,),  activation='tanh', solver='lbfgs',    alpha=0.001,batch_size='auto',
               learning_rate='constant', learning_rate_init=0.01, power_t=0.5, max_iter=1000, shuffle=True,
               random_state=None, tol=0.0001, verbose=False, warm_start=False, momentum=0.9,
               nesterovs_momentum=True, early_stopping=False, validation_fraction=0.1, beta_1=0.9, beta_2=0.999,
               epsilon=1e-08)

neural_net_model_1.fit(X_train, y_train)

print("Training score")
print(neural_net_model_1.score(X_train, y_train))
print("Test score")
print(neural_net_model_1.score(X_test, y_test))

Training score
-6.372680161348399e-14
Test score
-0.0008226406547557907

In [ ]:
print(neural_net_model_1.predict(X_test))
print("-"*10)
print(y_test)

[0.0794117 0.0794117 0.0794117 0.0794117 0.0794117 0.0794117 0.0794117
 0.0794117 0.0794117 0.0794117 0.0794117 0.0794117 0.0794117 0.0794117
 0.0794117 0.0794117 0.0794117 0.0794117]
----------
53    0.04
25   -0.12
49   -0.14
3    -0.19
75    0.46
70   -0.24
32   -0.33
1     0.72
64    0.19
38    0.00
7     0.10
65    0.06
35    0.07
58   -0.11
17    0.20
11    0.71
28    0.00
8    -0.14
Name: delta: calm to energetic, dtype: float64