In [32]:
import pandas

In [33]:
df = pandas.read_csv('../out/merged_data.csv')
# df.head(3)

In [34]:
labels = df.columns
# labels

In [35]:
X = df.loc[
    :,
    [
        'release_year', 'duration_ms.x', 'explicit', 
        'mode', 'speechiness', 'acousticness',
        'instrumentalness', 'liveness', 'valence',
        'tempo', 'time_signature'
    ]
] 
# X.head(3)

In [36]:
Y = df.loc[
    :,
    [
        'delta: sad to happy',
        'delta: calm to energetic',
        'delta: relaxed to stressed'
    ]
] 
# Y.head()

Split into training and not

Creating the model

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.5, random_state=2)

In [61]:
from sklearn import linear_model
from sklearn.multioutput import MultiOutputRegressor

base_estimator = linear_model.LinearRegression()
model_linear = MultiOutputRegressor(base_estimator)
model_linear.fit(X_train, y_train)

model_linear.score(X_train, y_train)

0.2607818331258006

Another Model

In [49]:
from sklearn.ensemble import GradientBoostingRegressor

model_gradient_boost = MultiOutputRegressor(GradientBoostingRegressor(random_state=0))
model_gradient_boost.fit(X_train, y_train)
model_gradient_boost.score(X_test, y_test)

-0.003950947986401239

In [51]:
pandas.DataFrame(model_gradient_boost.predict(X_test)).head()

          0         1         2
0  0.156636  0.481378  0.180564
1 -0.019230  0.523242 -0.140982
2  0.023412  0.094846 -0.209929
3 -0.027407  0.230431 -0.726405
4 -0.007211  0.171065  0.145324

In [53]:
y_test.head()

    delta: sad to happy  delta: calm to energetic  delta: relaxed to stressed
11                 0.47                      0.71                        0.33
0                  0.24                      0.27                        0.20
79                 0.14                      0.13                        0.16
29                 0.56                     -0.14                       -0.14
66                -0.12                     -0.06                       -0.09

Trying to just predict one column

In [68]:
y = Y['delta: sad to happy']

# Assuming X contains features and y contains labels
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=2)

In [65]:
from sklearn.linear_model import LinearRegression

model_linear = LinearRegression()
model_linear.fit(X_train, y_train)

model_linear.score(X_train, y_train)

0.26194815254975556

In [72]:
y = Y['delta: calm to energetic']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.8, random_state=2)

model_linear = LinearRegression()
model_linear.fit(X_train, y_train)

model_linear.score(X_train, y_train)

0.2146819302009898

In [ ]:
y = Y['delta: relaxed to stressed']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5, random_state=2)

from sklearn.linear_model import LinearRegression

model_linear = LinearRegression()
model_linear.fit(X_train, y_train)

model_linear.score(X_train, y_train)

0.24752338041641353