In [64]:
import pandas

In [65]:
df = pandas.read_csv('../out/merged_data.csv')
# df.head(3)

In [66]:
labels = df.columns
# labels

In [67]:
X = df.loc[
    :,
    [
        'release_year', 'duration_ms.x', 'explicit', 
        'mode', 'speechiness', 'acousticness',
        'instrumentalness', 'liveness', 'valence',
        'tempo', 'time_signature'
    ]
] 
# X.head(3)

In [68]:
Y = df.loc[
    :,
    [
        'delta: sad to happy',
        'delta: calm to energetic',
        'delta: relaxed to stressed'
    ]
] 
# Y.head()

Split into training and not

Creating the model

In [69]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.5, random_state=2)

In [70]:
from sklearn import linear_model
from sklearn.multioutput import MultiOutputRegressor

base_estimator = linear_model.LinearRegression()
model_linear = MultiOutputRegressor(base_estimator)
model_linear.fit(X_train, y_train)

model_linear.score(X_train, y_train)

0.2607818331258006

Another Model

In [ ]:
from sklearn.ensemble import GradientBoostingRegressor

model_gradient_boost = MultiOutputRegressor(GradientBoostingRegressor())
model_gradient_boost.fit(X_train, y_train)
print("Training score")
print(model_gradient_boost.score(X_train, y_train))
print("Test score")
print(model_gradient_boost.score(X_test, y_test))

Training score
0.9989130240395131
Test score
-0.05701248527392048

In [72]:
pandas.DataFrame(model_gradient_boost.predict(X_test)).head()

          0         1         2
0  0.112241  0.489046  0.184122
1 -0.023604  0.520731 -0.137995
2  0.025108  0.094846 -0.209929
3 -0.040813  0.181949 -0.884814
4 -0.007211  0.170681  0.116179

In [73]:
y_test.head()

    delta: sad to happy  delta: calm to energetic  delta: relaxed to stressed
11                 0.47                      0.71                        0.33
0                  0.24                      0.27                        0.20
79                 0.14                      0.13                        0.16
29                 0.56                     -0.14                       -0.14
66                -0.12                     -0.06                       -0.09

Trying to just predict one column

In [74]:
y = Y['delta: sad to happy']

# Assuming X contains features and y contains labels
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=2)

In [75]:
from sklearn.linear_model import LinearRegression

model_linear = LinearRegression()
model_linear.fit(X_train, y_train)

model_linear.score(X_train, y_train)

0.27422222981561495

In [ ]:
y = Y['delta: calm to energetic']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=2)

model_linear = LinearRegression()
model_linear.fit(X_train, y_train)

model_linear.score(X_train, y_train)

0.2146819302009898

In [83]:
y = Y['delta: relaxed to stressed']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5, random_state=2)

from sklearn.linear_model import LinearRegression

model_linear = LinearRegression()
model_linear.fit(X_train, y_train)
print("Training score")
print(model_linear.score(X_train, y_train))
print("Test score")
print(model_linear.score(X_test, y_test))

Training score
0.24752338041641353
Test score
0.13050809278760223